# Generated by Django 4.1 on 2023-05-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportedError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Layout", "Layout"),
                            ("animation", "animation"),
                            ("Links", "Link"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("description", models.TextField(max_length=500)),
                ("d_width", models.IntegerField()),
                ("d_height", models.IntegerField()),
                ("err_section", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="SkillType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="WorkedWith",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "level",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (40, "Beginner"),
                            (75, "Intermediate"),
                            (95, "Advance"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("color", models.CharField(blank=True, max_length=6, null=True)),
                ("skill_type", models.ManyToManyField(to="app.skilltype")),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("info", models.TextField(max_length=500)),
                (
                    "mobile_preview",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "tab_preview",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "pc_preview",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("p_link", models.URLField(max_length=100)),
                ("github_link", models.URLField(max_length=100)),
                ("worked_with", models.ManyToManyField(to="app.workedwith")),
            ],
        ),
        migrations.CreateModel(
            name="Design",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("worked_with", models.ManyToManyField(to="app.workedwith")),
            ],
        ),
    ]
