# Generated by Django 4.1 on 2023-05-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_design_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="p_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="worked_on",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
