# Generated by Django 4.1 on 2023-05-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_project_p_type_project_worked_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportederror",
            name="err_section",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
