# Generated by Django 4.1 on 2023-05-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_reportederror_err_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportederror",
            name="choice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Layout", "Layout"),
                    ("Animation", "Animation"),
                    ("Links", "Link"),
                    ("Option not available", "Option not available"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
